#!/bin/sh

# Note: I3_DIR is defined in .xsessionrc.d/i3.env

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
exec conky -c $I3_DIR/conkyrc
