#!/bin/bash

# should we be quiet?
if [ -e ~/.silent ] || [ -e ~/.quiet ];then 
	echo 'Found "~/.silent" or "~/.quiet". Not running any startup programs.' 1>&2
	exit 0
fi

i3-msg "workspace 3"
qbittorrent &
sleep 10  # Wait for qbittorent to finish starting

# Sync up X
xrefresh &

# Return home
i3-msg "workspace 1"


